"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import Image from "next/image";
const nav=[["hash","Hash"],["block","Block"],["blockchain","Blockchain"],["distributed","Distributed"],["tokens","Tokens"],["coinbase","Coinbase"],["keys","Keys"],["signatures","Signatures"],["transaction","Transaction"]];
const enc=(v:string)=>new TextEncoder().encode(v),hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join(""),sha=async(v:string)=>hex(await crypto.subtle.digest("SHA-256",enc(v)));
function Header({page}:{page:string}){return <header><Link className="brand" href="/hash"><Image src="/Corelia_Academy_Logo_White.png" alt="Corelia Academy" width={750} height={300} priority/><b>Blockchain Demo</b></Link><button className="menu" onClick={()=>document.querySelector("nav")?.classList.toggle("open")}>☰</button><nav>{nav.map(([slug,label],i)=><span key={slug} className={i===6?"split":""}><Link className={page===slug?"active":""} href={"/"+slug}>{label}</Link></span>)}</nav></header>}
function Card({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}){return <section className={"card "+className}><h2>{title}</h2>{children}</section>}
function HashDemo(){const[data,setData]=useState(""),[hash,setHash]=useState("");useEffect(()=>{sha(data).then(setHash)},[data]);return <Card title="SHA256 Hash"><label>Data<textarea rows={8} value={data} onChange={e=>setData(e.target.value)}/></label><label>Hash<input value={hash} readOnly/></label></Card>}
function BlockCard({index=1,token=false}:{index?:number;token?:boolean}){const initial=(token?[6267,4170,7448,4133,1595]:[1075,1866,4020,449,442])[index-1]??0,[nonce,setNonce]=useState(initial),[data,setData]=useState(token?"10.00  Alice → Bob":""),[hash,setHash]=useState(""),[mining,setMining]=useState(false),previous="0".repeat(64);useEffect(()=>{sha(`${index}${nonce}${data}${previous}`).then(setHash)},[index,nonce,data,previous]);async function mine(){setMining(true);let n=0,h="";do{n++;h=await sha(`${index}${n}${data}${previous}`)}while(!h.startsWith("000"));setNonce(n);setHash(h);setMining(false)}return <Card title={"Block #"+index} className={hash.startsWith("000")?"valid":"pending"}><div className="fieldRow"><label>Block<input value={index} readOnly/></label><label>Nonce<input value={nonce} onChange={e=>setNonce(Number(e.target.value))}/></label></div><label>{token?"Transactions":"Data"}<textarea rows={token?6:4} value={data} onChange={e=>setData(e.target.value)}/></label><label>Prev<input value={previous} readOnly/></label><label>Hash<input value={hash} readOnly/></label><button className="primary" onClick={mine} disabled={mining}>{mining?"Mining…":"Mine"}</button></Card>}
function Chain({distributed=false,token=false}:{distributed?:boolean;token?:boolean}){const peers=distributed?["Peer A","Peer B","Peer C"]:[""];return <>{peers.map(peer=><section className="peer" key={peer}>{peer&&<h2 className="peerTitle">{peer}</h2>}<div className="rail">{[1,2,3,4,5].map(n=><BlockCard key={peer+n} index={n} token={token}/>)}</div></section>)}</>}
function Keys(){const[pub,setPub]=useState(""),[priv,setPriv]=useState("");async function generate(){const p=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]);setPub(hex(await crypto.subtle.exportKey("spki",p.publicKey)));setPriv(hex(await crypto.subtle.exportKey("pkcs8",p.privateKey)))}useEffect(()=>{let active=true;crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]).then(async p=>{const [publicValue,privateValue]=await Promise.all([crypto.subtle.exportKey("spki",p.publicKey),crypto.subtle.exportKey("pkcs8",p.privateKey)]);if(active){setPub(hex(publicValue));setPriv(hex(privateValue))}});return()=>{active=false}},[]);return <Card title="Public / Private Key Pairs"><label>Private Key<div className="withButton"><input value={priv} readOnly/><button onClick={generate}>Random</button></div></label><label>Public Key<input value={pub} readOnly/></label></Card>}
function Signatures({transaction=false}:{transaction?:boolean}){const[pair,setPair]=useState<CryptoKeyPair|null>(null),[message,setMessage]=useState(transaction?"20.00 · Alice → Bob":"Hello blockchain"),[sig,setSig]=useState(""),[ok,setOk]=useState<boolean|null>(null);useEffect(()=>{crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]).then(setPair)},[]);async function sign(){if(pair)setSig(hex(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},pair.privateKey,enc(message))))}async function verify(){if(!pair||!sig)return;const bytes=new Uint8Array(sig.match(/.{1,2}/g)?.map(x=>parseInt(x,16))??[]);setOk(await crypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},pair.publicKey,bytes,enc(message)))}return <Card title={transaction?"Transaction":"Signatures"} className={ok===true?"valid":ok===false?"invalid":""}><div className="tabs"><b>Sign</b><span>Verify</span></div><label>{transaction?"Transaction":"Message"}<textarea rows={5} value={message} onChange={e=>{setMessage(e.target.value);setOk(null)}}/></label><div className="actions"><button className="primary" onClick={sign}>Sign</button><button onClick={verify} disabled={!sig}>Verify</button></div><label>Message Signature<input value={sig} readOnly/></label>{ok!==null&&<p className={ok?"success":"error"}>{ok?"Signature verified.":"Invalid signature."}</p>}</Card>}

type Tx={value:string;from:string;to:string};
type LedgerBlock={index:number;nonce:number;transactions:Tx[];previous:string;hash:string;coinbase?:{value:string;to:string}};
const tokenSeed:LedgerBlock[]=[
 {index:1,nonce:139358,transactions:[{value:"25.00",from:"Darcy",to:"Bingley"},{value:"4.27",from:"Elizabeth",to:"Jane"},{value:"19.22",from:"Wickham",to:"Lydia"},{value:"106.44",from:"Lady Catherine de Bourgh",to:"Collins"},{value:"6.42",from:"Charlotte",to:"Elizabeth"}],previous:"0".repeat(64),hash:""},
 {index:2,nonce:39207,transactions:[{value:"97.67",from:"Ripley",to:"Lambert"},{value:"48.61",from:"Kane",to:"Ash"},{value:"6.15",from:"Parker",to:"Dallas"},{value:"10.44",from:"Hicks",to:"Newt"},{value:"88.32",from:"Bishop",to:"Burke"},{value:"45.00",from:"Hudson",to:"Gorman"},{value:"92.00",from:"Vasquez",to:"Apone"}],previous:"00000c52990ee86de55ec4b9b32beefd745d71675dc0eddfbc7b88336e2e296b",hash:""},
 {index:3,nonce:13804,transactions:[{value:"10.00",from:"Emily",to:"Jackson"},{value:"5.00",from:"Madison",to:"Jackson"},{value:"20.00",from:"Lucas",to:"Grace"}],previous:"000078be183417844c14a9251ca246fb15df1074019873f5d85c1a6f4311d4e0",hash:""},
 {index:4,nonce:20688,transactions:[{value:"62.19",from:"Rick",to:"Ilsa"},{value:"867.96",from:"Captain Louis Renault",to:"Strasser"},{value:"276.15",from:"Victor Laszlo",to:"Ilsa"},{value:"97.13",from:"Rick",to:"Sam"},{value:"119.63",from:"Captain Louis Renault",to:"Jan Brandel"}],previous:"0000c2c95f54a49b4f2bee7056a7dc3b7c1a408706c848b520e20eac75aaceb0",hash:""},
 {index:5,nonce:33083,transactions:[{value:"14.12",from:"Denise Lovett",to:"Edmund Lovett"},{value:"2,760.29",from:"Lord Glendenning",to:"John Moray"},{value:"413.78",from:"Katherine Glendenning",to:"Miss Audrey"}],previous:"0000c03019ed59586405750968888fb65256e82492480d9fe0a6bd2f5e86b5ca",hash:""}
];
const coinbaseSeed:LedgerBlock[]=[
 {index:1,nonce:16651,coinbase:{value:"100.00",to:"Anders"},transactions:[],previous:"0".repeat(64),hash:""},
 {index:2,nonce:215458,coinbase:{value:"100.00",to:"Anders"},transactions:[{value:"10.00",from:"Anders",to:"Sophia"},{value:"20.00",from:"Anders",to:"Lucas"},{value:"15.00",from:"Anders",to:"Emily"},{value:"15.00",from:"Anders",to:"Madison"}],previous:"0000438d7625b86a6f366545b1929975a0d3ff1f8847e56cc587cadddb0ab781",hash:""},
 {index:3,nonce:146,coinbase:{value:"100.00",to:"Anders"},transactions:[{value:"10.00",from:"Emily",to:"Jackson"},{value:"5.00",from:"Madison",to:"Jackson"},{value:"20.00",from:"Lucas",to:"Grace"}],previous:"0000baeab68c2a60f9a6fa56355438d97c672a15494fcea617064d9314f9ff63",hash:""},
 {index:4,nonce:18292,coinbase:{value:"100.00",to:"Anders"},transactions:[{value:"15.00",from:"Jackson",to:"Ryan"},{value:"5.00",from:"Emily",to:"Madison"},{value:"8.00",from:"Sophia",to:"Jackson"}],previous:"0000df1d632b734f5a5fc126a0f0e8894fb4c8314ba7086b62980559af6771b9",hash:""},
 {index:5,nonce:108899,coinbase:{value:"100.00",to:"Sophia"},transactions:[{value:"2.00",from:"Jackson",to:"Alexander"},{value:"6.00",from:"Ryan",to:"Carter"},{value:"4.00",from:"Ryan",to:"Riley"},{value:"9.95",from:"Grace",to:"Katherine"}],previous:"0000c694336f88129f3685bd3ba5d67c445dfd8d18bd22f5d87301dd560eb30e",hash:""}
];
const cloneSeed=(seed:LedgerBlock[])=>seed.map(b=>({...b,coinbase:b.coinbase?{...b.coinbase}:undefined,transactions:b.transactions.map(t=>({...t}))}));
const ledgerText=(b:LedgerBlock)=>`${b.index}${b.nonce}${b.coinbase?.value??""}${b.coinbase?.to??""}${b.transactions.map(t=>`${t.value}${t.from}${t.to}`).join("")}${b.previous}`;

function Ledger({coinbase=false}:{coinbase?:boolean}){
 const seed=coinbase?coinbaseSeed:tokenSeed;
 const[peers,setPeers]=useState<LedgerBlock[][]>(()=>["A","B","C"].map(()=>cloneSeed(seed)));
 const[mining,setMining]=useState("");
 useEffect(()=>{let active=true;const initial=["A","B","C"].map(()=>cloneSeed(coinbase?coinbaseSeed:tokenSeed));(async()=>{const ready=await Promise.all(initial.map(async chain=>Promise.all(chain.map(async b=>({...b,hash:await sha(ledgerText(b))})))));if(active)setPeers(ready)})();return()=>{active=false}},[coinbase]);
 async function recalc(chain:LedgerBlock[],start:number){const next=cloneSeed(chain);for(let i=start;i<next.length;i++){if(i>0)next[i].previous=next[i-1].hash;next[i].hash=await sha(ledgerText(next[i]))}return next}
 async function edit(peer:number,block:number,change:(b:LedgerBlock)=>void){const all=peers.map(cloneSeed);change(all[peer][block]);all[peer]=await recalc(all[peer],block);setPeers(all)}
 async function mine(peer:number,block:number){const key=`${peer}-${block}`;setMining(key);const all=peers.map(cloneSeed),target=all[peer][block];let nonce=0,hash="";do{target.nonce=nonce++;hash=await sha(ledgerText(target))}while(!hash.startsWith("0000"));target.nonce=nonce-1;target.hash=hash;all[peer]=await recalc(all[peer],block+1);setPeers(all);setMining("")}
 return <>{peers.map((chain,p)=><section className="peer" key={p}><h2 className="peerTitle">Peer {String.fromCharCode(65+p)}</h2><div className="rail">{chain.map((b,i)=><Card key={b.index} title={"Block #"+b.index} className={b.hash.startsWith("0000")?"valid":"pending"}><div className="fieldRow"><label>Block<input value={b.index} readOnly/></label><label>Nonce<input value={b.nonce} onChange={e=>edit(p,i,x=>{x.nonce=Number(e.target.value)})}/></label></div>{b.coinbase&&<label>Coinbase<div className="transactionRow coinbaseRow"><span>$</span><input aria-label="Coinbase value" value={b.coinbase.value} onChange={e=>edit(p,i,x=>{if(x.coinbase)x.coinbase.value=e.target.value})}/><span>→</span><input aria-label="Coinbase recipient" value={b.coinbase.to} onChange={e=>edit(p,i,x=>{if(x.coinbase)x.coinbase.to=e.target.value})}/></div></label>}<label>Tx<div className="transactions">{b.transactions.map((tx,t)=><div className="transactionRow" key={t}><span>$</span><input aria-label="Transaction value" value={tx.value} onChange={e=>edit(p,i,x=>{x.transactions[t].value=e.target.value})}/><span>From</span><input aria-label="Transaction sender" value={tx.from} onChange={e=>edit(p,i,x=>{x.transactions[t].from=e.target.value})}/><span>→</span><input aria-label="Transaction recipient" value={tx.to} onChange={e=>edit(p,i,x=>{x.transactions[t].to=e.target.value})}/></div>)}</div></label><label>Prev<input value={b.previous} readOnly/></label><label>Hash<input value={b.hash} readOnly/></label><button className="primary" disabled={!!mining} onClick={()=>mine(p,i)}>{mining===`${p}-${i}`?"Mining…":"Mine"}</button></Card>)}</div></section>)}</>
}

export default function Demo({page}:{page:string}){let content:React.ReactNode;switch(page){case"hash":content=<HashDemo/>;break;case"block":content=<BlockCard/>;break;case"blockchain":content=<Chain/>;break;case"distributed":content=<Chain distributed/>;break;case"tokens":content=<Ledger/>;break;case"coinbase":content=<Ledger coinbase/>;break;case"keys":content=<Keys/>;break;case"signatures":content=<Signatures/>;break;default:content=<Signatures transaction/>}const narrow=["hash","block","keys","signatures","transaction"].includes(page),title=page==="coinbase"?"Coinbase Transactions":nav.find(n=>n[0]===page)?.[1];return <><Header page={page}/><main className={"container "+(narrow?"":"fluid")}><div className="pageTitle"><h1>{title}</h1></div>{content}</main></>}
